apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor-project-lifecycle
  labels:
    k8s-app: monitor-project-lifecycle
spec:
  selector:
    matchLabels:
      app: monitor-project-lifecycle
  namespaceSelector:
    matchNames:
    - openshift
  endpoints:
  - port: web
    interval: 10s
